### ISSUE TITLE
如果在mac上，你的这些命令该怎么写？

### ISSUE THREAD

**Issue by luckypoem** [aturl/awesome-anti-gfw#1]
sudo ip link del dev wg0
sudo ip route del 12.34.56.78 via 192.168.1.1
sudo ip route del default
sudo ip route add default via 192.168.1.1

ref: https://github.com/aturl/awesome-anti-gfw/blob/master/WireGuard_VPN_Tunnel.md

**Comment by aturl** [comment]
WireGuard 目前不支持 macOS 系统，要等 Rust 或 Golang 的版本。
